%% QUESTIONNAIREANALYSIS 

addpath('..\');
[params] = GetParameters();
addpath('..\plot');
load('..\..\data\questionnaireData.mat');


%% Friedman ANOVA for sense of ownership



%% sense of ownership - full arm static vs full arm dynamic
[comparisonResults] = statisticsQuestionnaires (...
    squeeze(static_orderedResponses(params.quest.owner, 1, :)), ...
    squeeze(dynamic_orderedResponses(params.quest.owner, 1, :))...
    );

plotQuestionnaires(...
    squeeze(static_orderedResponses(params.quest.owner, 1, :)), ...
    squeeze(dynamic_orderedResponses(params.quest.owner, 1, :)), ...
    'Sense of Ownership', params.conditionStatic{1,1}, ...
    params.conditionDynamic{1, 1}, comparisonResults.stats);

results.Ownership.statifull_dynamicfull = comparisonResults;
results.Ownership.statifull_dynamicfull.Condition1 = params.conditionStatic{1, 1};
results.Ownership.statifull_dynamicfull.Condition2 = params.conditionDynamic{1, 1};


%% sense of ownership (static) - full arm vs detached hand 
[comparisonResults] = statisticsQuestionnaires (...
    squeeze(static_orderedResponses(params.quest.owner, 1, :)), ...
    squeeze(static_orderedResponses(params.quest.owner, 2, :))...
    );

plotQuestionnaires(...
    squeeze(static_orderedResponses(params.quest.owner, 1, :)), ...
    squeeze(static_orderedResponses(params.quest.owner, 2, :)), ...
    'Sense of Ownership', params.conditionStatic{1,1}, ...
    params.conditionStatic{1,2}, comparisonResults.stats);

results.Ownership.staticfull_staticdetached = comparisonResults;
results.Ownership.staticfull_staticdetached.Condition1 = params.conditionStatic{1, 1};
results.Ownership.staticfull_staticdetached.Condition2 = params.conditionStatic{1, 2};


%% sense of ownership - detached hand static vs detached hand dynamic
[comparisonResults] = statisticsQuestionnaires (...
    squeeze(static_orderedResponses(params.quest.owner, 2, :)), ...
    squeeze(dynamic_orderedResponses(params.quest.owner, 2, :))...
    );

plotQuestionnaires(...
    squeeze(static_orderedResponses(params.quest.owner, 2, :)), ...
    squeeze(dynamic_orderedResponses(params.quest.owner, 2, :)), ...
    'Sense of Ownership', params.conditionStatic{1,2}, ...
    params.conditionDynamic{1, 2}, comparisonResults.stats);

results.Ownership.staticdetached_dynamicdetached = comparisonResults;
results.Ownership.staticdetached_dynamicdetached.Condition1 = params.conditionStatic{1, 2};
results.Ownership.staticdetached_dynamicdetached.Condition2 = params.conditionDynamic{1, 2};


%% sense of ownership (dynamic) - full arm vs detached hand
[comparisonResults] = statisticsQuestionnaires (...
    squeeze(dynamic_orderedResponses(params.quest.owner, 1, :)), ...
    squeeze(dynamic_orderedResponses(params.quest.owner, 2, :))...
    );

plotQuestionnaires(...
    squeeze(dynamic_orderedResponses(params.quest.owner, 1, :)), ...
    squeeze(dynamic_orderedResponses(params.quest.owner, 2, :)), ...
    'Sense of Ownership', params.conditionDynamic{1, 1}, ...
    params.conditionDynamic{1, 2}, comparisonResults.stats);

results.Ownership.dynamicfull_dynamicdetached = comparisonResults;
results.Ownership.dynamicfull_dynamicdetached.Condition1 = params.conditionDynamic{1, 1};
results.Ownership.dynamicfull_dynamicdetached.Condition2 = params.conditionDynamic{1, 2};


%% sense of ownership (static) - full arm vs post
[comparisonResults] = statisticsQuestionnaires (...
    squeeze(static_orderedResponses(params.quest.owner, 1, :)), ...
    squeeze(static_orderedResponses(params.quest.owner, 3, :))...
    );

plotQuestionnaires(...
    squeeze(static_orderedResponses(params.quest.owner, 1, :)), ...
    squeeze(static_orderedResponses(params.quest.owner, 3, :)), ...
    'Sense of Ownership', params.conditionStatic{1, 1}, ...
    params.conditionStatic{1, 3}, comparisonResults.stats);

results.Ownership.staticfull_staticpost = comparisonResults;
results.Ownership.staticfull_staticpost.Condition1 = params.conditionStatic{1, 1};
results.Ownership.staticfull_staticpost.Condition2 = params.conditionStatic{1, 3};


%% sense of ownership (dynamic) - full arm vs incongruent movement
[comparisonResults] = statisticsQuestionnaires (...
    squeeze(dynamic_orderedResponses(params.quest.owner, 1, :)), ...
    squeeze(dynamic_orderedResponses(params.quest.owner, 3, :))...
    );

plotQuestionnaires(...
    squeeze(dynamic_orderedResponses(params.quest.owner, 1, :)), ...
    squeeze(dynamic_orderedResponses(params.quest.owner, 3, :)), ...
    'Sense of Ownership', params.conditionDynamic{1, 1}, ...
    params.conditionDynamic{1, 3}, comparisonResults.stats);

results.Ownership.dynamicfull_incongruent = comparisonResults;
results.Ownership.dynamicfull_incongruent.Condition1 = params.conditionDynamic{1, 1};
results.Ownership.dynamicfull_incongruent.Condition2 = params.conditionDynamic{1, 3};


%% Sense of agency (static) - Full arm vs detached hand
[comparisonResults] = statisticsQuestionnaires (...
    squeeze(static_orderedResponses(params.quest.agenStat, 1, :)), ...
    squeeze(static_orderedResponses(params.quest.agenStat, 2, :))...
    );

plotQuestionnaires(...
    squeeze(static_orderedResponses(params.quest.agenStat, 1, :)), ...
    squeeze(static_orderedResponses(params.quest.agenStat, 2, :)), ...
    'Sense of Agency', params.conditionStatic{1, 1}, ...
    params.conditionStatic{1, 2}, comparisonResults.stats);

results.Agency.staticfull_staticdetached = comparisonResults;
results.Agency.staticfull_staticdetached.Condition1 = params.conditionStatic{1, 1};
results.Agency.staticfull_staticdetached.Condition2 = params.conditionStatic{1, 2};


%% sense of agency (static) - full arm vs full arm post
[comparisonResults] = statisticsQuestionnaires (...
    squeeze(static_orderedResponses(params.quest.agenStat, 1, :)), ...
    squeeze(static_orderedResponses(params.quest.agenStat, 3, :))...
    );

plotQuestionnaires(...
    squeeze(static_orderedResponses(params.quest.agenStat, 1, :)), ...
    squeeze(static_orderedResponses(params.quest.agenStat, 3, :)), ...
    'Sense of Agency', params.conditionStatic{1, 1}, ...
    params.conditionStatic{1, 3}, comparisonResults.stats);

results.Agency.staticfull_staticpost = comparisonResults;
results.Agency.staticfull_staticpost.Condition1 = params.conditionStatic{1, 1};
results.Agency.staticfull_staticpost.Condition2 = params.conditionStatic{1, 3};


%% sense of agency (dynamic) - full arm dynamic vs detached hand dynamic
[comparisonResults] = statisticsQuestionnaires (...
    squeeze(dynamic_orderedResponses(params.quest.agenDyn, 1, :)), ...
    squeeze(dynamic_orderedResponses(params.quest.agenDyn, 2, :))...
    );

plotQuestionnaires(...
    squeeze(dynamic_orderedResponses(params.quest.agenDyn, 1, :)), ...
    squeeze(dynamic_orderedResponses(params.quest.agenDyn, 2, :)), ...
    'Sense of Agency', params.conditionDynamic{1, 1}, ...
    params.conditionDynamic{1, 2}, comparisonResults.stats);

results.Agency.dynamicfull_dynamicdetached = comparisonResults;
results.Agency.dynamicfull_dynamicdetached.Condition1 = params.conditionStatic{1, 1};
results.Agency.dynamicfull_dynamicdetached.Condition2 = params.conditionStatic{1, 2};


%% sense of agency (dynamic) - full arm dynamic vs incongruent movement
[comparisonResults] = statisticsQuestionnaires (...
    squeeze(dynamic_orderedResponses(params.quest.agenDyn, 1, :)), ...
    squeeze(dynamic_orderedResponses(params.quest.agenDyn, 3, :))...
    );

plotQuestionnaires(...
    squeeze(dynamic_orderedResponses(params.quest.agenDyn, 1, :)), ...
    squeeze(dynamic_orderedResponses(params.quest.agenDyn, 3, :)), ...
    'Sense of Agency', params.conditionDynamic{1, 1}, ...
    params.conditionDynamic{1, 3}, comparisonResults.stats);

results.Agency.dynamicfull_incongruent = comparisonResults;
results.Agency.dynamicfull_incongruent.Condition1 = params.conditionStatic{1, 1};
results.Agency.dynamicfull_incongruent.Condition2 = params.conditionStatic{1, 3};


%% sense of agency (outcome) - full arm dynamic vs detached hand dynamic

% The Friedman ANOVA was not significant. 

% [comparisonResults] = statisticsQuestionnaires (...
%     squeeze(dynamic_orderedResponses(params.quest.agenOut, 1, :)), ...
%     squeeze(dynamic_orderedResponses(params.quest.agenOut, 2, :))...
%     );
% 
% plotQuestionnaires(...
%     squeeze(dynamic_orderedResponses(params.quest.agenOut, 1, :)), ...
%     squeeze(dynamic_orderedResponses(params.quest.agenOut, 2, :)), ...
%     'Sense of Agency Outcome', params.conditionDynamic{1, 1}, ...
%     params.conditionDynamic{1, 2}, comparisonResults.stats);
% 
% results.OutcomeAgency.dynamicfull_dynamicdetached = comparisonResults;
% results.OutcomeAgency.dynamicfull_dynamicdetached.Condition1 = params.conditionStatic{1, 1};
% results.OutcomeAgency.dynamicfull_dynamicdetached.Condition2 = params.conditionStatic{1, 2};


%% sense of agency (outcome) - full arm dynamic vs incongruent movement

% The Friedman ANOVA was not significant. 

% [comparisonResults] = statisticsQuestionnaires (...
%     squeeze(dynamic_orderedResponses(params.quest.agenOut, 1, :)), ...
%     squeeze(dynamic_orderedResponses(params.quest.agenOut, 3, :))...
%     );
% 
% plotQuestionnaires(...
%     squeeze(dynamic_orderedResponses(params.quest.agenOut, 1, :)), ...
%     squeeze(dynamic_orderedResponses(params.quest.agenOut, 3, :)), ...
%     'Sense of Agency Outcome', params.conditionDynamic{1, 1}, ...
%     params.conditionDynamic{1, 3}, comparisonResults.stats);
% 
% results.OutcomeAgency.dynamicfull_incongruent = comparisonResults;
% results.OutcomeAgency.dynamicfull_incongruent.Condition1 = params.conditionStatic{1, 1};
% results.OutcomeAgency.dynamicfull_incongruent.Condition2 = params.conditionStatic{1, 3};


%% correlations difference

[results.correlations.staticfull_staticdetached]= correlationDifference(...
    nanmean(squeeze(static_orderedResponses(params.quest.owner, 1, :))) - ...
    nanmean(squeeze(static_orderedResponses(params.quest.owner, 2, :))), ...
    nanmean(squeeze(static_orderedResponses(params.quest.agenStat, 1, :))) - ...
    nanmean(squeeze(static_orderedResponses(params.quest.agenStat, 2, :))));

[results.correlations.dynamicfull_dynamicdetached]= correlationDifference(...
    nanmean(squeeze(dynamic_orderedResponses(params.quest.owner, 1, :))) - ...
    nanmean(squeeze(dynamic_orderedResponses(params.quest.owner, 2, :))), ...
    nanmean(squeeze(dynamic_orderedResponses(params.quest.agenDyn, 1, :))) - ...
    nanmean(squeeze(dynamic_orderedResponses(params.quest.agenDyn, 2, :))));

[results.correlations.dynamicfull_incongruent]= correlationDifference(...
    nanmean(squeeze(dynamic_orderedResponses(params.quest.owner, 1, :))) - ...
    nanmean(squeeze(dynamic_orderedResponses(params.quest.owner, 3, :))), ...
    nanmean(squeeze(dynamic_orderedResponses(params.quest.agenDyn, 1, :))) - ...
    nanmean(squeeze(dynamic_orderedResponses(params.quest.agenDyn, 3, :))));


%% Save Variables
save('..\..\data\results.mat', 'results');

